//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOInvoiceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.Invoice = new HashSet<Invoice>();
        }
    
        public int id { get; set; }
        public string OrgNo { get; set; }
        public string name { get; set; }
        public string InvoiceName { get; set; }
        public string InvoiceAddress { get; set; }
        public string InvoicePostNo { get; set; }
        public string InvoicePostAddress { get; set; }
        public string InvoiceEmail { get; set; }
        public Nullable<int> InvoiceDefaultPaymentTermsDays { get; set; }
        public Nullable<System.DateTime> Founded { get; set; }
        public Nullable<bool> StorKund { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoice { get; set; }
    }
}
