//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPOInvoiceWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int id { get; set; }
        public int InvoiceNo { get; set; }
        public System.DateTime Datum { get; set; }
        public int company_id { get; set; }
        public System.DateTime Duedate { get; set; }
        public int PaymentTermsDays { get; set; }
        public string OurReference { get; set; }
        public string YourReference { get; set; }
        public string OcrNo { get; set; }
        public double TotalExVat { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<double> Vat { get; set; }
        public string InvoiceRowText { get; set; }
        public string InvoiceName { get; set; }
        public string InvoiceAddress { get; set; }
        public string InvoicePostNo { get; set; }
        public string InvoicePostAddress { get; set; }
        public string InvoiceEmail { get; set; }
        public string OrgNo { get; set; }
        public string YourVatNo { get; set; }
    
        public virtual Company Company { get; set; }
    }
}
